USE [master]
GO
/****** Object:  Database [UNITAREAS]    Script Date: 5/2/2025 5:48:14 p. m. ******/
CREATE DATABASE [UNITAREAS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UNITAREAS', FILENAME = N'/var/opt/mssql/data/UNITAREAS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UNITAREAS_log', FILENAME = N'/var/opt/mssql/data/UNITAREAS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [UNITAREAS] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UNITAREAS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [UNITAREAS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [UNITAREAS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [UNITAREAS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [UNITAREAS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [UNITAREAS] SET ARITHABORT OFF 
GO
ALTER DATABASE [UNITAREAS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [UNITAREAS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [UNITAREAS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [UNITAREAS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [UNITAREAS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [UNITAREAS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [UNITAREAS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [UNITAREAS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [UNITAREAS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [UNITAREAS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [UNITAREAS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [UNITAREAS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [UNITAREAS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [UNITAREAS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [UNITAREAS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [UNITAREAS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [UNITAREAS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [UNITAREAS] SET RECOVERY FULL 
GO
ALTER DATABASE [UNITAREAS] SET  MULTI_USER 
GO
ALTER DATABASE [UNITAREAS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [UNITAREAS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [UNITAREAS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [UNITAREAS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [UNITAREAS] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [UNITAREAS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [UNITAREAS] SET QUERY_STORE = ON
GO
ALTER DATABASE [UNITAREAS] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [UNITAREAS]
GO
/****** Object:  Table [dbo].[Estado]    Script Date: 5/2/2025 5:48:17 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estado](
	[EstadoID] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[EstadoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Roles]    Script Date: 5/2/2025 5:48:17 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[RoleID] [int] IDENTITY(1,1) NOT NULL,
	[NombreRol] [varchar](50) NOT NULL,
	[Descripcion] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[RoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 5/2/2025 5:48:17 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[Usuario] [nvarchar](50) NOT NULL,
	[NombreCompleto] [nvarchar](300) NOT NULL,
	[Telefono] [numeric](15, 0) NOT NULL,
	[PasswordHash] [varbinary](256) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
	[RoleID] [int] NOT NULL,
	[EstadoID] [int] NOT NULL,
	[FechaCreacion] [datetime] NOT NULL,
	[UsuarioCreaID] [int] NULL,
	[FechaModificacion] [datetime] NULL,
	[UsuarioModificaID] [int] NULL,
 CONSTRAINT [PK__Usuarios__1788CCAC2ABC2A4C] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__Usuarios__6B0F5AE0A0698736] UNIQUE NONCLUSTERED 
(
	[Usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__Usuarios__A9D10534029A4B52] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Usuarios] ADD  CONSTRAINT [DF__Usuarios__FechaC__4F7CD00D]  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [dbo].[Usuarios]  WITH CHECK ADD  CONSTRAINT [FK__Usuarios__Estado__5165187F] FOREIGN KEY([EstadoID])
REFERENCES [dbo].[Estado] ([EstadoID])
GO
ALTER TABLE [dbo].[Usuarios] CHECK CONSTRAINT [FK__Usuarios__Estado__5165187F]
GO
ALTER TABLE [dbo].[Usuarios]  WITH CHECK ADD  CONSTRAINT [FK__Usuarios__RoleID__5070F446] FOREIGN KEY([RoleID])
REFERENCES [dbo].[Roles] ([RoleID])
GO
ALTER TABLE [dbo].[Usuarios] CHECK CONSTRAINT [FK__Usuarios__RoleID__5070F446]
GO
ALTER TABLE [dbo].[Usuarios]  WITH CHECK ADD  CONSTRAINT [FK__Usuarios__Usuari__52593CB8] FOREIGN KEY([UsuarioCreaID])
REFERENCES [dbo].[Usuarios] ([UserID])
GO
ALTER TABLE [dbo].[Usuarios] CHECK CONSTRAINT [FK__Usuarios__Usuari__52593CB8]
GO
ALTER TABLE [dbo].[Usuarios]  WITH CHECK ADD  CONSTRAINT [FK__Usuarios__Usuari__534D60F1] FOREIGN KEY([UsuarioModificaID])
REFERENCES [dbo].[Usuarios] ([UserID])
GO
ALTER TABLE [dbo].[Usuarios] CHECK CONSTRAINT [FK__Usuarios__Usuari__534D60F1]
GO
USE [master]
GO
ALTER DATABASE [UNITAREAS] SET  READ_WRITE 
GO
